repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        args: [--line-length=120]
        exclude: (^old_cegid/|^old_cegid$)

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: [--fix]
        types_or: [ python, pyi ] # to exclude ipynb files
        exclude: (^old_cegid/|^old_cegid$|some_tests/)

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
